development:
    dialect: mysql
    dir: ./
    datasource: root:root@tcp(127.0.0.1)/mycard?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
    dialect: postgres
    dir: ./postgres
    datasource: dbname=myapp sslmode=disable
    table: migrations